apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  DB_USERNAME: {{ .Values.postgresql.auth.username }}
  DB_HOST: "db"
  DB_PORT: "{{ .Values.postgresql.primary.service.port }}"
  DB_NAME: {{ .Values.postgresql.auth.database }}
  CORS_ALLOWED_ORIGIN: "{{ .Values.cors.allowed.origin }}"