apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}-frontend-config
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  config.js: |
    window.__CONFIG__ = {
      API_URL: "http://localhost:8080"
    };
