apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DB_USERNAME: "admin"
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  CORS_ALLOWED_ORIGIN: "*"
  AWS_S3_BUCKET_NAME: "florin-zamf-demo-bucket"
  AWS_REGION: "eu-central-1"
  AWS_S3_ENDPOINT: ""
