image:
  repository: docker.io/library/backend
  tag: "9.0"
  pullPolicy: Never
replicaCount: 1

service:
  #schimbat din ClusterIP in NodePort pentru a putea accesa serviciul din afara clusterului k8s pentru prometheus
  type: NodePort
  port: 8080

cors:
  allowed:
    origin: "*"

postgresql:
  auth:
    username: admin
    password: adminpass
    database: postgres
  primary:
    service:
      port: 5432
    persistence:
      enabled: true
      storageClass: standard
      size: 2Gi

aws:
  s3:
    name: florin-zamf-demo-bucket
  region: eu-central-1

ingress:
  enabled: true

httpRoute:
  enabled: false